version: "3"

networks:

    network-shinobi-academy:

        external: false

services:

    shinobi-academy-database:

        container_name: shinobi-academy-database

        image: softwareshinobi/shinobi-academy-database

        build: 

            context: .

            dockerfile: Dockerfile

        restart: unless-stopped

        networks:

            - network-shinobi-academy

        ports:

            - 3306:3306

        environment:

            MYSQL_ROOT_PASSWORD: aggiepride

            MYSQL_DATABASE: shinobiacademy

            MYSQL_USER: shinobiacademy

            MYSQL_PASSWORD: shinobiacademy

    shinobi-academy-phpmyadmin:

        container_name: shinobi-academy-phpmyadmin

        image: beeyev/phpmyadmin-lightweight
        
        restart: unless-stopped

        depends_on:

            - shinobi-academy-database

        networks:

            - network-shinobi-academy

        ports:

            - 8888:80

        environment:

            PMA_HOST: shinobi-academy-database

            MYSQL_ROOT_PASSWORD: aggiepride
