pipeline {
    agent any

    stages {

        stage('Run Script') {
            
            steps {
                   sh 'pwd'
                   sh 'chmod +x ./build-automation/build-pass-1-build-docker-image-from-dockerfile.sh'
                   sh 'cd build-automation;./build-pass-1-build-docker-image-from-dockerfile.sh'
            }
    
        }
    
    }

}
