pipeline {
    agent any

    stages {


                stage('Run 1111') {
            
            steps {
                                   
                   sh 'chmod +x ./build-automation/*.sh'                        
                
            }
    
        }
        
        stage('Run Scrip2222t') {
            
            steps {
                                                   
                   sh 'cd build-automation;./build-pass-1-build-docker-image-from-dockerfile.sh'
                
            }
    
        }
            stage('Run Scrssssip2222t') {
            
            steps {
                                                   
                   sh 'cd build-automation;./build-pass-3-build-docker-image-from-dockerfile.sh'
                
            }
    
        }
    }

}
